WCS\CoavBundle\Entity\Terrain:
    type: entity
    table: null
    repositoryClass: WCS\CoavBundle\Repository\TerrainRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        icao:
            type: string
            length: '4'
            nullable: true
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }

    oneToMany:
        departures:
            targetEntity: WCS\CoavBundle\Entity\Flight
            mappedBy: departure
        arrivals:
            targetEntity: WCS\CoavBundle\Entity\Flight
            mappedBy: arrival
